version: '3.8'

services:
  n8n:
    build: .
    container_name: n8n-c
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - GENERIC_TIMEZONE=Asia/Shanghai
      - DB_TYPE=sqlite
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_WORKFLOWS_FOLDER=/home/node/workflow
    volumes:
      - ./.n8n:/home/node/.n8n
      - ./workflow:/home/node/workflow
